name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Cache backend deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-backend-${{ hashFiles('./package-lock.json','./lambda/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-backend-

      - name: Install backend dependencies
        run: npm run deps:backend

      - name: Build backend
        run: npm run build:backend

      - name: Deploy backend
        run: npm run deploy:backend

      - name: Cache frontend deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('./client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-frontend-

      - name: Install frontend dependencies
        run: npm run deps:frontend

      - name: Build frontend
        run: npm run build:frontend

      - name: Deploy frontend
        run: npm run deploy:frontend
